/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.SalidaRecursos;
import controlador.Ctrl_SalidaRecursos;
import controlador.SalidaRecursosPDF;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author julio
 */
public class InterSalidaRecursos extends javax.swing.JInternalFrame {

    private int IDSALIDARECURSOS;
    int obtenerIDRECURSOCombo= 0;

    /**
     * Creates new form InterSalidaRecursos
     */
    public InterSalidaRecursos() {
        initComponents();
        this.setSize(new Dimension(750, 600));
        this.setTitle("Salida de Recursos");
        
        this.CargarTablaSalidaRecursos();
        this.CargarComboRecurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_CANTIDAD = new javax.swing.JTextField();
        txt_EmpSer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SalidaRecursos = new javax.swing.JTable();
        jButton_GenerarReporte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_REGISTRAR = new javax.swing.JButton();
        jComboBox_RECU = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_CODIGO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DESCRIPCION = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_NOMBRE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_COLOR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_CANTIDAD_DIS = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Salida de Materia Prima ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Responsable:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Recurso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad Disponible:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 230, -1, -1));
        getContentPane().add(txt_CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 170, -1));
        getContentPane().add(txt_EmpSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jTable_SalidaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_SalidaRecursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalidaRecursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_SalidaRecursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 680, 190));

        jButton_GenerarReporte.setBackground(new java.awt.Color(51, 255, 255));
        jButton_GenerarReporte.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_GenerarReporte.setText("Generar Reporte");
        jButton_GenerarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_GenerarReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 170, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Actualizar.setText("ACTUALIZAR");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        jButton_REGISTRAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_REGISTRAR.setText("REGISTRAR");
        jButton_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_REGISTRARActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 180, 140));

        jComboBox_RECU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Recurso" }));
        getContentPane().add(jComboBox_RECU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Codigo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));
        getContentPane().add(txt_CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripción:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, -1));
        getContentPane().add(txt_DESCRIPCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));
        getContentPane().add(txt_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 170, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setText("Color:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        getContentPane().add(txt_COLOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setText("Cantidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, -1));
        getContentPane().add(txt_CANTIDAD_DIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_SalidaRecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalidaRecursosMouseClicked

        
    }//GEN-LAST:event_jTable_SalidaRecursosMouseClicked

    private void jButton_GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenerarReporteActionPerformed
        SalidaRecursosPDF pdf = new SalidaRecursosPDF();
        pdf.DatosSalidaRecursos(IDSALIDARECURSOS);
        pdf.generarReproteSalidaRecursosPDF();        
    }//GEN-LAST:event_jButton_GenerarReporteActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        String recur ="";
        recur =jComboBox_RECU.getSelectedItem().toString().trim();
        if (txt_EmpSer.getText().equals("") || txt_CANTIDAD.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{
            try {
                SalidaRecursos salidaRecursos = new SalidaRecursos();
                Ctrl_SalidaRecursos controlSalidaRecursos = new Ctrl_SalidaRecursos();
                salidaRecursos.setEMPSERV(txt_EmpSer.getText().trim());
                salidaRecursos.setRECURSO(jComboBox_RECU.getSelectedItem().toString().trim());
                salidaRecursos.setCANTIDAD(Integer.parseInt(txt_CANTIDAD.getText()));
                salidaRecursos.setESTADO(1);

                if (controlSalidaRecursos.actualizar(salidaRecursos,IDSALIDARECURSOS)) {
                    JOptionPane.showMessageDialog(null, "Registro Actualizado");
                    this.CargarTablaSalidaRecursos();
                    this.Limpiar();      
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Actualizar");
                }

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error en: " + e);
            }
   
   
        }
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        Ctrl_SalidaRecursos controlSalidaRecursos = new Ctrl_SalidaRecursos();
        if (IDSALIDARECURSOS == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione Correctamente!");
        } else {
            if (!controlSalidaRecursos.eliminar(IDSALIDARECURSOS)) {
                JOptionPane.showMessageDialog(null, "¡Salida de recurso Eliminado!");
                this.CargarTablaSalidaRecursos();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar salida de recurso!");
            }
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_REGISTRARActionPerformed
        // TODO add your handling code here:
        SalidaRecursos salidaRecursos = new SalidaRecursos();
        Ctrl_SalidaRecursos controlSalidaRecursos = new Ctrl_SalidaRecursos();
        String recu ="";
        recu =jComboBox_RECU.getSelectedItem().toString().trim();
        if (txt_EmpSer.getText().equals("")  || txt_CANTIDAD.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{
            try {
                salidaRecursos.setEMPSERV(txt_EmpSer.getText().trim());
                salidaRecursos.setRECURSO(jComboBox_RECU.getSelectedItem().toString().trim());
                salidaRecursos.setCANTIDAD(Integer.parseInt(txt_CANTIDAD.getText()));
                salidaRecursos.setESTADO(1);

                if (controlSalidaRecursos.guardar(salidaRecursos)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    this.CargarTablaSalidaRecursos();
                    this.Limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardare");
                }

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error en: " + e);
            }
        }
    }//GEN-LAST:event_jButton_REGISTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_GenerarReporte;
    private javax.swing.JButton jButton_REGISTRAR;
    private javax.swing.JComboBox<String> jComboBox_RECU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_SalidaRecursos;
    private javax.swing.JTextField txt_CANTIDAD;
    private javax.swing.JTextField txt_CANTIDAD_DIS;
    private javax.swing.JTextField txt_CODIGO;
    private javax.swing.JTextField txt_COLOR;
    private javax.swing.JTextField txt_DESCRIPCION;
    private javax.swing.JTextField txt_EmpSer;
    private javax.swing.JTextField txt_NOMBRE;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_EmpSer.setText("");

        txt_CANTIDAD.setText("");

    }

    private void CargarTablaSalidaRecursos() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select IDSALIDARECURSOS, EMPSERV, RECURSO, CANTIDAD, ESTADO from SALIRECTABLA";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterSalidaRecursos.jTable_SalidaRecursos = new JTable(model);
            InterSalidaRecursos.jScrollPane1.setViewportView(InterSalidaRecursos.jTable_SalidaRecursos);

            model.addColumn("N°");//ID
            model.addColumn("Empleado/Servicio");
            model.addColumn("RECURSO");
            model.addColumn("CANTIDAD");
            model.addColumn("ESTADO");

            while (rs.next()) {

                Object fila[] = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla Salida de Recursos: " + e);
        }
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_SalidaRecursos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_SalidaRecursos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    IDSALIDARECURSOS = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosSalidaRecursoSeleccionado(IDSALIDARECURSOS);//metodo
                }
            }
        });
    }

    private void EnviarDatosSalidaRecursoSeleccionado(int IDSALIDARECURSOS) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from SALIRECTABLA where IDSALIDARECURSOS = '" + IDSALIDARECURSOS + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txt_EmpSer.setText(rs.getString("EMPSERV"));
                int idrecu = rs.getInt("IDRECURSO");
                jComboBox_RECU.setSelectedItem(relacionarRecurso(idrecu));
                txt_CANTIDAD.setText(rs.getString("CANTIDAD"));

            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar Salida de Recurso: " + e);
        }
    }
    String NombreRecurso ="";
    private String relacionarRecurso(int IDRECURSO) {

        String sql = "select NOMBRE from tb_recursos where IDRECURSO = '" + IDRECURSO + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                NombreRecurso = rs.getString("NOMBRE");
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("¡Error al obtener el id del recurso!");
        }
        return NombreRecurso;
    }
    private int IdRecurso() {
        String sql = "select * from tb_recursos where NOMBRE = '" + this.jComboBox_RECU.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIDRECURSOCombo = rs.getInt("IDRECURSO");
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener IDPRODUCTO");
        }
        return obtenerIDRECURSOCombo;
    }
    private void CargarComboRecurso() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_recursos";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_RECU.removeAllItems();
            jComboBox_RECU.addItem("Seleccione Recurso:");
            while (rs.next()) {
                jComboBox_RECU.addItem(rs.getString("NOMBRE"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("¡Error al cargar producto !" + e);
        }
    }

}
