/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Servicios;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.Servicios;

/**
 *
 * @author julio
 */
public class InterServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterServicios
     */
    public InterServicios() {
        initComponents();
        this.setSize(new Dimension(400, 313));
        this.setTitle("Registrar Servicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_DNI = new javax.swing.JTextField();
        txt_APELLIDO = new javax.swing.JTextField();
        txt_DIRECCION = new javax.swing.JTextField();
        txt_TELEFONO = new javax.swing.JTextField();
        txt_ESTADO = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        txt_NOMBRE = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DNI:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));
        getContentPane().add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, -1));
        getContentPane().add(txt_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, -1));
        getContentPane().add(txt_DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, -1));
        getContentPane().add(txt_TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, -1));
        getContentPane().add(txt_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, -1));

        jButton_Guardar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registrar.jpg"))); // NOI18N
        jButton_Guardar.setText("GUARDAR");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 30));
        getContentPane().add(txt_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
        Servicios servicios = new Servicios();
        Ctrl_Servicios controlServicios = new Ctrl_Servicios();
        if (txt_DNI.getText().equals("") || txt_NOMBRE.getText().equals("") || txt_APELLIDO.getText().equals("")
                || txt_DIRECCION.getText().equals("") || txt_TELEFONO.getText().equals("") || txt_ESTADO.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            try {
                servicios.setDNI(txt_DNI.getText().trim());
                servicios.setNOMBRE(txt_NOMBRE.getText().trim());
                servicios.setAPELLIDO(txt_APELLIDO.getText().trim());

                servicios.setDIRECCION(txt_DIRECCION.getText().trim());
                servicios.setTELEFONO(txt_TELEFONO.getText().trim());
                servicios.setESTADO(txt_ESTADO.getText().trim());
                servicios.setStdo(1);

                if (controlServicios.guardar(servicios)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    

                    this.Limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error en: " + e);
            }
        }
    }//GEN-LAST:event_jButton_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_APELLIDO;
    private javax.swing.JTextField txt_DIRECCION;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_ESTADO;
    private javax.swing.JTextField txt_NOMBRE;
    private javax.swing.JTextField txt_TELEFONO;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {

        txt_DNI.setText("");
        txt_NOMBRE.setText("");
        txt_APELLIDO.setText("");
        txt_DIRECCION.setText("");
        txt_TELEFONO.setText("");
        txt_ESTADO.setText("");
    }
}
