package vista;

import conexion.Conexion;
import controlador.Ctrl_Proveedores;
import controlador.Ctrl_Servicios;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Servicios;

/**
 *
 * @author ediso
 */
public class InterGestionarServicios extends javax.swing.JInternalFrame {

    private int IDSERVICIOS; //usar metodo actualizar

    public InterGestionarServicios() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Servicios");
        //Cargar tabla
        this.CargarTablaServicios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Servicios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_DNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_NOMBRE = new javax.swing.JTextField();
        txt_APELLIDO = new javax.swing.JTextField();
        txt_TELEFONO = new javax.swing.JTextField();
        txt_ESTADO = new javax.swing.JTextField();
        txt_DIRECCION = new javax.swing.JTextField();
        txt_buscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestionar Servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Servicios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar.jpg"))); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.jpg"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 150, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DNI:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        txt_DNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_DNI.setEnabled(false);
        jPanel3.add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Apellido:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        txt_NOMBRE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        txt_APELLIDO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 170, -1));

        txt_TELEFONO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 170, -1));

        txt_ESTADO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 170, -1));

        txt_DIRECCION.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 170, -1));

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        jPanel3.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Buscar:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        Servicios servicios = new Servicios();
        Ctrl_Servicios controlServicios = new Ctrl_Servicios();
        if (txt_NOMBRE.getText().equals("") || txt_APELLIDO.getText().equals("") || txt_DNI.getText().equals("")
                || txt_DIRECCION.getText().equals("") || txt_TELEFONO.getText().equals("") || txt_ESTADO.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            try {
                servicios.setNOMBRE(txt_NOMBRE.getText().trim());
                servicios.setAPELLIDO(txt_APELLIDO.getText().trim());
                servicios.setDNI(txt_DNI.getText().trim());
                servicios.setDIRECCION(txt_DIRECCION.getText().trim());
                servicios.setTELEFONO(txt_TELEFONO.getText().trim());
                servicios.setESTADO(txt_ESTADO.getText().trim());
                servicios.setStdo(1);

                if (controlServicios.actualizar(servicios,IDSERVICIOS)) {
                    JOptionPane.showMessageDialog(null, "Registro Actualizado");
                    //CARGARServicios
                    this.CargarTablaServicios();
                    this.Limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Actualizar");
                }

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error en: " + e);
            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        Ctrl_Servicios controlServicios = new Ctrl_Servicios();
        if (IDSERVICIOS == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un Servicio!");
        } else {
            if (!controlServicios.eliminar(IDSERVICIOS)) {
                JOptionPane.showMessageDialog(null, "¡Servicio Eliminado!");
                this.CargarTablaServicios();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar servicio!");
            }
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        BuscarServicios(txt_buscar.getText());
    }//GEN-LAST:event_txt_buscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Servicios;
    private javax.swing.JTextField txt_APELLIDO;
    private javax.swing.JTextField txt_DIRECCION;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_ESTADO;
    private javax.swing.JTextField txt_NOMBRE;
    private javax.swing.JTextField txt_TELEFONO;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_DNI.setText("");
        txt_NOMBRE.setText("");
        txt_APELLIDO.setText("");
        txt_DIRECCION.setText("");
        txt_TELEFONO.setText("");
        txt_ESTADO.setText("");
        
    }

    private void CargarTablaServicios() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select IDSERVICIOS, NOMBRE, APELLIDO, DNI, DIRECCION, TELEFONO, ESTADO, Stdo from tb_servicio";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarServicios.jTable_Servicios = new JTable(model);
            InterGestionarServicios.jScrollPane1.setViewportView(InterGestionarServicios.jTable_Servicios);

            model.addColumn("N°");//ID
            model.addColumn("NOMBRE");
            model.addColumn("APELLIDO");
            model.addColumn("DNI");
            model.addColumn("DIRECCION");
            model.addColumn("TELEFONO");
            model.addColumn("ESTADO");
            model.addColumn("Stdo");

            while (rs.next()) {


                Object fila[] = new Object[8];
                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla Servicios: " + e);
        }
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_Servicios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_Servicios.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    IDSERVICIOS = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosServicioSeleccionado(IDSERVICIOS);//metodo
                }
            }
        });
    }

    private void EnviarDatosServicioSeleccionado(int IDSERVICIOS) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from tb_servicio where IDSERVICIOS = '" + IDSERVICIOS + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txt_NOMBRE.setText(rs.getString("NOMBRE"));
                txt_APELLIDO.setText(rs.getString("APELLIDO"));
                txt_DNI.setText(rs.getString("DNI"));
                txt_TELEFONO.setText(rs.getString("TELEFONO"));
                txt_DIRECCION.setText(rs.getString("DIRECCION"));
                txt_ESTADO.setText(rs.getString("ESTADO"));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar Servicios: " + e);
        }
    }
    
    public void BuscarServicios(String buscar){
        Ctrl_Servicios ctrl_Servicios =new Ctrl_Servicios();
        DefaultTableModel modelo=ctrl_Servicios.buscarServicios(buscar);
        jTable_Servicios.setModel(modelo);
    }

}
