/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import controlador.Ctrl_Servicio;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Servicios;
import static vista.InterGestionarServicio.jTable_servicio;

/**
 *
 * @author julio
 */
public class InterGestionarServicio extends javax.swing.JInternalFrame {

    private int IDSERVICIO;

    /**
     * Creates new form InterGestionarServicio
     */
    public InterGestionarServicio() {
        initComponents();
        this.CargarTablaServicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_servicio = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ESTADO = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        txt_NOMBRE = new javax.swing.JTextField();
        txt_APELLIDO = new javax.swing.JTextField();
        txt_DIRECCION = new javax.swing.JTextField();
        txt_TELEFONO = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel1.setText("Gestionar Servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jTable_servicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_servicio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 650, 260));

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));
        getContentPane().add(txt_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 150, -1));
        getContentPane().add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 150, -1));
        getContentPane().add(txt_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 412, 150, 20));
        getContentPane().add(txt_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 150, -1));
        getContentPane().add(txt_DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 150, -1));
        getContentPane().add(txt_TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 150, -1));

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        if (txt_DNI.getText().isEmpty() && txt_NOMBRE.getText().isEmpty()
                && txt_APELLIDO.getText().isEmpty() && txt_DIRECCION.getText().isEmpty() && txt_TELEFONO.getText().isEmpty() && txt_ESTADO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Completa todos los campos!");
        } else {

            Servicios servicio = new Servicios();
            Ctrl_Servicio controlServicio = new Ctrl_Servicio();

            servicio.setDNI(txt_DNI.getText().trim());
            servicio.setNOMBRE(txt_NOMBRE.getText().trim());
            servicio.setAPELLIDO(txt_APELLIDO.getText().trim());
            servicio.setDIRECCION(txt_DIRECCION.getText().trim());
            servicio.setTELEFONO(txt_TELEFONO.getText().trim());
            servicio.setESTADO(txt_ESTADO.getText().trim());
            servicio.setStdo(1);

            if (controlServicio.actualizar(servicio, IDSERVICIO)) {
                JOptionPane.showMessageDialog(null, "¡Datos del cliente actualizados!");
                this.CargarTablaServicio();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al actualizar!");
            }

        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        Ctrl_Servicio controlServicio = new Ctrl_Servicio();
        if (IDSERVICIO == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un cliente!");
        } else {
            if (!controlServicio.eliminar(IDSERVICIO)) {
                JOptionPane.showMessageDialog(null, "¡Cliente Eliminado!");
                this.CargarTablaServicio();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar cliente!");
                this.Limpiar();
            }
        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_servicio;
    private javax.swing.JTextField txt_APELLIDO;
    private javax.swing.JTextField txt_DIRECCION;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_ESTADO;
    private javax.swing.JTextField txt_NOMBRE;
    private javax.swing.JTextField txt_TELEFONO;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_DNI.setText("");
        txt_NOMBRE.setText("");
        txt_APELLIDO.setText("");
        txt_DIRECCION.setText("");
        txt_TELEFONO.setText("");
        txt_ESTADO.setText("");
    }

    private void CargarTablaServicio() {
        Connection cn = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select IDSERVICIOS, DNI, NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTADO, Stdo from tb_servicio";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarServicio.jTable_servicio = new JTable(model);
            InterGestionarServicio.jScrollPane1.setViewportView(InterGestionarServicio.jTable_servicio);

            model.addColumn("N°");//ID
            model.addColumn("DNI");
            model.addColumn("NOMBRE");
            model.addColumn("APELLIDO");
            model.addColumn("DIRECCION");
            model.addColumn("TELEFONO");
            model.addColumn("ESTADO");
            model.addColumn("Stdo");

            while (rs.next()) {
                Object fila[] = new Object[8];
                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla servicio: " + e);
        }
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_servicio.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_servicio.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    IDSERVICIO = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosServicioSeleccionado(IDSERVICIO);//metodo
                }
            }
        });
    }

    private void EnviarDatosServicioSeleccionado(int IDSERVICIO) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from tb_servicio where IDSERVICIOS = '" + IDSERVICIO + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txt_DNI.setText(rs.getString("DNI"));
                txt_NOMBRE.setText(rs.getString("NOMBRE"));
                txt_APELLIDO.setText(rs.getString("APELLIDO"));
                txt_DIRECCION.setText(rs.getString("DIRECCION"));
                txt_TELEFONO.setText(rs.getString("TELEFONO"));
                txt_ESTADO.setText(rs.getString("ESTADO"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar servicio: " + e);
        }
    }

}
